import { build } from 'esbuild';
import { mkdir, copyFile, cp } from 'node:fs/promises';
import { htmlToImageCsp } from './html-to-image-csp.mjs';
await mkdir('dist', { recursive: true });
await build({ entryPoints: ['src/content.js'], outfile: 'dist/content.js', bundle: true, format: 'iife', target: 'chrome120', minify: true, loader: { '.css': 'text', '.svg': 'text', '.png': 'dataurl' }, legalComments: 'eof', plugins: [htmlToImageCsp] });
await build({ entryPoints: ['src/popup.js'], outfile: 'dist/popup.js', bundle: true, format: 'iife', target: 'chrome120', minify: true });
await cp('public/_locales', 'dist/_locales', { recursive: true });
await cp('public/icons', 'dist/icons', { recursive: true });
await copyFile('public/manifest.json', 'dist/manifest.json');
await copyFile('public/popup.html', 'dist/popup.html');
console.log('Extension built in dist/');
